# roles/loadbalancer/tasks/main.yml

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Configure HAProxy to load balance to frontend servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: true
