---
- name: Configure Database Server
  hosts: database
  become: yes

  tasks:
    # Install MySQL Server and additional packages
    - name: Install MySQL Server and other packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - curl
        - unzip
      update_cache: yes

    # Configure SSH settings
    - name: Disable root login over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Allow password authentication over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH

    # Install SSL certificate
    - name: Copy company SSL certificate
      copy:
        src: /path/to/company_cert.crt
        dest: /etc/ssl/certs/company_cert.crt
        mode: '0644'

    # Configure Message of the Day (MOTD)
    - name: Set MOTD banner
      copy:
        content: |
          Welcome to the Costco server!
          Unauthorized access is prohibited.
        dest: /etc/motd
        mode: '0644'

    # Secure MySQL installation
    - name: Secure MySQL installation
      mysql_secure_installation:
        login_user: root
        login_password: ''
        new_password: 'YourDBSecurePassword123!'
        change_root_password: yes
        remove_anonymous_users: yes
        disallow_root_login_remotely: yes
        remove_test_db: yes

    # Create a sample database
    - name: Create a sample database
      mysql_db:
        name: webapp_db
        state: present
        login_user: root
        login_password: 'YourDBSecurePassword123!'

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
