---
- name: Configure Load Balancer
  hosts: loadbalancer
  become: yes

  tasks:
    # Install HAProxy and additional packages
    - name: Install HAProxy and additional packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - curl
        - unzip
      update_cache: yes

    # Configure SSH settings
    - name: Disable root login over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Allow password authentication over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH

    # Install SSL certificate
    - name: Copy company SSL certificate
      copy:
        src: /path/to/company_cert.crt
        dest: /etc/ssl/certs/company_cert.crt
        mode: '0644'

    # Configure Message of the Day (MOTD)
    - name: Set MOTD banner
      copy:
        content: |
          Welcome to the Costco server!
          Unauthorized access is prohibited.
        dest: /etc/motd
        mode: '0644'

    # Configure HAProxy for frontend load balancing
    - name: Configure HAProxy for frontend load balancing
      copy:
        content: |
          frontend http_front
              bind *:80
              default_backend servers

          backend servers
              balance roundrobin
              server frontend1 10.0.0.5:80 check
              server frontend2 10.0.0.6:80 check
              server frontend3 10.0.0.7:80 check
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
